name: Scaffold Service

on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'The name of the service'
        required: true
        default: 'my-service'
        minLength: 3
        maxLength: 50
        pattern: '^[a-zA-Z0-9]([-_a-zA-Z0-9]{1,48})[a-zA-Z0-9]$'
      programming_language:
        description: 'Programming language for the service'
        required: true
        default: 'Python'
      author_name:
        description: 'Author email'
        required: true
      license:
        description: 'License type'
        required: true
        default: 'MIT'
      version:
        description: 'Initial version of the service'
        required: true
        default: '0.1.0'
        minLength: 5
        maxLength: 20
        pattern: '^(\d+\.\d+\.\d+(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?)$'
      repository_visibility:
        description: 'Repository visibility'
        required: true
        default: 'public'
      port_context:
        description: 'Port context information'
        required: false
        default: '{}'

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      run: |
        git clone https://github.com/${{ github.repository }} .
        curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
        -H "Content-Type: application/json" \
        -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
        -d '{"message": "Checked out repository."}'

    - name: Set up Python
      run: |
        if [ "${{ inputs.programming_language }}" == "Python" ]; then
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
          -d '{"message": "Set up Python environment."}'
        fi

    - name: Set up Node.js
      run: |
        if [ "${{ inputs.programming_language }}" == "JavaScript" ]; then
          curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
          -d '{"message": "Set up Node.js environment."}'
        fi

    - name: Notify PORT - Start
      run: |
        curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
        -H "Content-Type: application/json" \
        -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
        -d '{"message": "Scaffolding service started..."}'

    - name: Scaffold service
      run: |
        echo "Scaffolding service..."
        curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
        -H "Content-Type: application/json" \
        -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
        -d '{"message": "Service scaffolding initiated."}'
        
        echo "Service Name: ${{ inputs.service_name }}"
        echo "Programming Language: ${{ inputs.programming_language }}"
        echo "Author: ${{ inputs.author_name }}"
        echo "License: ${{ inputs.license }}"
        echo "Version: ${{ inputs.version }}"
        echo "Repository Visibility: ${{ inputs.repository_visibility }}"
        echo "Port Context: ${{ inputs.port_context }}"

        mkdir ${{ inputs.service_name }}
        cd ${{ inputs.service_name }}

        curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
        -H "Content-Type: application/json" \
        -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
        -d '{"message": "Created service directory ${{ inputs.service_name }}."}'

        case ${{ inputs.license }} in
          "MIT")
            curl -o LICENSE https://opensource.org/licenses/MIT
            echo "MIT License created."
            curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
            -d '{"message": "MIT License file created."}'
            ;;
          "Apache-2.0")
            curl -o LICENSE https://www.apache.org/licenses/LICENSE-2.0.txt
            echo "Apache-2.0 License created."
            curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
            -d '{"message": "Apache-2.0 License file created."}'
            ;;
          "GPL-3.0")
            curl -o LICENSE https://www.gnu.org/licenses/gpl-3.0.txt
            echo "GPL-3.0 License created."
            curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
            -d '{"message": "GPL-3.0 License file created."}'
            ;;
          *)
            echo "License type not supported. Please add manually."
            curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
            -d '{"message": "License type not supported. Please add manually."}'
            ;;
        esac
        
        echo ${{ inputs.version }} > VERSION
        echo "Version file created."
        curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
        -H "Content-Type: application/json" \
        -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
        -d '{"message": "Version file created."}'

        if [ "${{ inputs.programming_language }}" == "Python" ]; then
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          echo "print('Hello, world!')" > main.py
          echo "Python project scaffolded."
          curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
          -d '{"message": "Python project scaffolded."}'
        elif [ "${{ inputs.programming_language }}" == "JavaScript" ]; then
          npm init -y
          echo "console.log('Hello, world!');" > index.js
          echo "JavaScript project scaffolded."
          curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
          -H "Content-Type: application/json" \
          -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
          -d '{"message": "JavaScript project scaffolded."}'
        fi

        git init
        echo "Initialized Git repository."
        curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
        -H "Content-Type: application/json" \
        -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
        -d '{"message": "Initialized Git repository."}'
        
        git config user.name 'Dan Amzulescu'
        git config user.email '${{ inputs.author_email }}'
        git add .
        git commit -m "Initial commit"
        echo "Committed initial files to Git."
        curl -X POST https://api.getport.io/v1/actions/runs/${{ fromJson(inputs.port_context).runId }}/logs \
        -H "Content-Type: application/json" \
        -H "Authorization: ${{ secrets.PORT_JWT_TOKEN }}" \
        -d '{"message": "Committed initial files to Git."}'
